on:
  push:
    tags:
      - v*

name: Test, build, publish
jobs:
  master:
    name: Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: install
    - name: Build and test
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: test
    - name: Publish
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
